const std::string names[] = {
"Friendzone {n}",
"{n} The Demon",
"Hold my {n}",
"{n} The wizard",
"Leave {n} alone",
"SmolPP {n}",
"{n} The golden",
"BigPP {n}",
"{n} From mars",
"{n} The scientist",
"Dont slap {n}",
"{n} The slapper",
"Call me {n}",
"{n} with milk",
"Master {n}",
"I am {n}",
"L {n}",
"I dropped my {n}",
"General {n}",
"Low battery {n}",
"{n} the liar",
"{n} in disguise",
"{n} the troll",
"{n} the fool",
"{n} the stinky",
"{n}.com",
"{n}is stinky",
"{n} the warrior",
"{n} the negotiator",
"fake {n}",
"{n} the clicker",
"waiting for {n}",
"{n} the unfunny",
"king {n}",
"doctor {n}",
"lolol {n} rofl",
"dont talk to {n}",
"do you smell {n}",
"solver rank {n}",
"gold rank {n}",
"{n} from fortnite",
"i think its {n}",
"{n} the simp",
"{n} the gamer",
"{n} the fragile",
"headshot {n}",
"my name is {n}",
"i pooped my {n}",
"prince {n}",
"{n} likes mappacks",
"{n} from the cave",
"{n} with cheese",
"{n} the lonely",
"{n} the trickster",
"serious {n}",
"{n} the warlock",
"{n} the avenger",
"{n} knows de way",
"{n} got 22",
"{n} on a potato",
"crackhead {n}",
"captain {n}",
"{n} from minecraft",
"{n} from terraria",
"{n} the friendly",
"sewer rat {n}",
"dont slap {n}",
"Ignore {n}",
"Dislike {n}",
"Slap {n}",
"I am not {n}",
"{n} the clicker",
"waiting for {n}",
"{n} is unavailable",
"MediumPP {n}",
"Dont call me {n}",
"{n}net",
"youtubecom/{n}",
"Dont mention {n}",
"Scream {n}",
"{n} the funny",
"{n} is the one",
"{n} the challenger",
"{n} hasnt beaten retray",
"{n} the hoker",
"{n} the noob",
"{n} the pro",
"DiscoNinja {n}",
"ProfessorPineapple {n}",
"JellyBeanJuggler {n}",
"CountFluffykins {n}",
"SizzlingCheeseburger {n}",
"DoctorSquishyFace {n}",
"PogoStickPrincess {n}",
"BaronVonBubbles {n}",
"SnickerdoodleSultan {n}",
"ZestyZombie {n}",
"TwinkleToesTaco {n}",
"LordOfTheLlamas {n}",
"{n} danced flamboyantly",
"{n} ate spaghetti",
"{n} chased unicorns",
"{n} sang off-key",
"{n} juggled chickens",
"{n} wore socks",
"{n} befriended aliens",
"{n} rode ostriches",
"{n} tickled penguins",
"{n} painted rainbows",
"{n} built sandcastles",
"{n} wrestled octopuses",
"{n} jumped joyfully",
"{n} twirled gracefully",
"{n} baked pancakes",
"{n} surfed clouds",
"{n} the Banana",
"Silly {n}",
"{n} the Clown",
"Funky {n}",
"Goofy {n}",
"{n} the Chuckle",
"Bubbly {n}",
"{n} the Wacky",
"Jolly {n}",
"{n} the Giggles",
"Snazzy {n}",
"{n} the Whimsy",
"Zany {n}",
"{n} the Snicker",
"Quirky {n}",
"{n} the Laughter",
"Cheeky {n}",
"{n} the Grin",
"Dizzy {n}",
"{n} the Chucklehead",
"Merry {n}",
"{n} the Smirk",
"Nutty {n}",
"{n} the Chuckler",
"Bouncy {n}",
"{n} the Chuckleberry",
"Witty {n}",
"{n} the Guffaw",
"Hilarious {n}",
"{n} the Chortle",
"Snappy {n}",
"{n} the Teehee",
"Gleeful {n}",
"{n} the Snigger",
"Giddy {n}",
"{n} the Snickerdoodle",
"Chucklesome {n}",
"{n} the Snort",
"Clownish {n}",
"{n} the Bellylaugh",
"Joyful {n}",
"{n} the Chucklenut",
"Frivolous {n}",
"{n} the Laughterbox",
"Jocular {n}",
"{n} the Chortler",
"Snickerdoodle {n}",
"{n} the Hilarity",
"Snickering {n}",
"{n} the mysterious",
"{n} the smelly",
"{n} is annoyed",
"{n} is president",
"{n} for real",
"Who is {n} anyway",
"{n} the Nooblet",
"Glitched {n}",
"{n} Just landed",
"Press my {n}",
"{n} is Grinding",
"Definitely not {n}",
"{n} on Mobile",
"Please ignore {n}",
"{n} is AFK",
"Secretly not {n}",
"Accidental {n}",
"Prisoner {n}",
"Dont touch {n}",
"{n} snuck in",
"Player {n} joined",
"Im hunting {n}",
"{n} Miabulo",
"Noob {n}",
"Real {n}",
"Press my {n}",
"Running from {n}",
"{n} the jedi",
"Looking for {n}",
"{n} Has lag",
"{n} Is lagging",
"{n} was here",
"{n} was taken",
"{n} got trolled",
"{n} is trolling",
"U make {n} angry",
"Your sidekick {n}",
"{n} for fake",
"{n} is banned",
"Smells like {n}",
"{n} just landed",
"{n} brought pizza",
"Look at {n}",
"{n} the tiny",
"{n} the unready",
"{n} but worse",
"Player {n} quit",
"{n} is lost",
"I hurt my {n}",
"{n} the derp",
"Better than {n}",
"{n} cant play",
"Your buddy {n}",
"{n} or whatever",
"{n} used fireball",
"Finding {n}",
"{n} the traitor",
"{n} is eating",
"Dont ignore {n}",
"{n} needs you ",
"{n} henchman",
"Unskilled {n}",
"{n} has a skill issue",
"{n} crashed at 97%",
"Stop {n}",
"{n} is ready",
"{n} wins",
"Loser {n}",
"{n} fell off",
"{n} is crazy"
};